Repository cloudfoundry/istio-release, pull requests merged in 2019-02, with the labels that each got.

#6 GCP load balancer healthchecks target router port 8002
  ci/planpatches/terraform/istio-router.tf
  deploy/bbl-config/terraform/istio-router.tf
Labels: scheduled

#9 istio routers node id meet requirements for Pilot
  jobs/envoy/templates/bpm.yml.erb
  jobs/envoy/templates/envoy.json.erb
Labels: unscheduled

#10 Configure maximum number of open files
  jobs/envoy/spec
  jobs/envoy/templates/bpm.yml.erb
Labels: unscheduled

#12 Configure mcp dns address
  jobs/copilot/spec
  jobs/pilot-discovery/templates/mesh-config.json.erb
Labels: in progress

#11 Configure envoy to use statsd to report metrics
  jobs/envoy/spec
  jobs/envoy/templates/envoy.json.erb
  spec/envoy.json.erb_spec.rb
Labels: unscheduled
